services:
  - type: web
    name: productivity-tips-api
    env: node
    plan: free
    repo: https://github.com/crcastle/productivity-tips-api
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /_health
    envVars:
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: NODE_ENV
        value: production # We need this during build, but Render sets it only during runtime
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false

  - type: web
    name: productivity-tips-web
    env: node
    plan: free
    repo: https://github.com/crcastle/productivity-tips-web
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: STRAPI_URL_BASE
        fromService:
          type: web
          name: productivity-tips-api
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: strapi
    plan: free # This database will expire 90 days after creation
